dist: xenial
language: ruby
sudo: false

cache: bundler

bundler_args: --jobs 3 --retry 3

before_install:
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"

script: "bundle exec rake"

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - truffleruby

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_edge.gemfile
